import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Box, Typography } from '@mui/material'
import Image from 'next/image';






const welcomeCard = {
  backgroundColor: "var(--theme-primary-light)",
  // border: "1px solid var(--theme-primary)",
  padding: "4rem",
  borderRadius: "1.5rem",
  color: "white"
}


export default function Home() {
  return (
    <>
      <Head>
        <title>DJ Shubham | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box sx={{ height: "auto", height: "15rem", backgroundColor: "black" }}>
          <Box className='banner-image'>
            <Image
              src="/img/banner2.png"
              width={400}
              height={200}
              alt="website banner"
              style={{ width: "100%", height: "100%" }}
            />
          </Box>

          <Box>
            <marquee className="moving-text">
              किसी भी गाने में अपना नाम लगवायें मात्र 100 रुपये में | 
            </marquee>
          </Box>
        </Box>

      </main>
    </>
  )
}
